### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bilaljalal** [samplecm/PlanNCheck#2]
Hello
I tried to build the solution and I am getting the following errors:

Resource file "Properties\Resources.resx" cannot be found.	Plan_n_Check			
also Calculate\Calculator.cs can't be found
can you please upload these files and fix the code

**Comment by samplecm** [comment]
Hi, sorry about that, I had forgotten to upload the files in properties. Added them now. I reuploaded Calculate/Calculator.cs again so hopefully it works now.
Thanks, and let me know if you encounter more issues.

**Comment by bilaljalal** [comment]
Thank you very much for your direct reply
still there is one file missing
Error	CS2001	Source file 'C:\Users\Desktop\PlanNCheck-master\Calculate\Calculator.cs' could not be found.

**Comment by bilaljalal** [comment]
https://user-images.githubusercontent.com/38360257/109350909-65e08e00-7889-11eb-83cb-704cf4b8ca31.png

**Comment by samplecm** [comment]
Thanks for raising the issue. My mistake, I had the wrong name for the directory on GITHUB for that file. I've changed it so hopefully it works now.

**Comment by bilaljalal** [comment]
Thank you very much for your spontaneous reply, 
still, there are some errors
1>C:\Users\Desktop\2021\PlanNCheck-master\Plan_n_Check.cs(975,44,975,58): error CS1061: 'ROI' does not contain a definition for 'HasSubsegments' and no accessible extension method 'HasSubsegments' accepting a first argument of type 'ROI' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Desktop\2021\PlanNCheck-master\Plan_n_Check.cs(1282,56,1282,70): error CS1061: 'ROI' does not contain a definition for 'HasSubsegments' and no accessible extension method 'HasSubsegments' accepting a first argument of type 'ROI' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Desktop\2021\PlanNCheck-master\Plan_n_Check.cs(1301,56,1301,70): error CS1061: 'ROI' does not contain a definition for 'HasSubsegments' and no accessible extension method 'HasSubsegments' accepting a first argument of type 'ROI' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Desktop\2021\PlanNCheck-master\Plan_n_Check.cs(1320,56,1320,70): error CS1061: 'ROI' does not contain a definition for 'HasSubsegments' and no accessible extension method 'HasSubsegments' accepting a first argument of type 'ROI' could be found (are you missing a using directive or an assembly reference?)

**Comment by samplecm** [comment]
Hi Bilaljalal, sorry for the delayed response. I have updated these files now so this issue should be fixed!

**Comment by samplecm** [comment]
Issue has been fixed
